import type { ModelDefinition } from '@contentrain/types'
import type { DataModule } from './data-emitter.js'

export function emitRuntimeModule(models: ModelDefinition[], dataModules: DataModule[]): string {
  const lines: string[] = [
    '// Auto-generated by @contentrain/query — do not edit manually',
    '',
  ]

  // Import data modules
  for (const dm of dataModules) {
    const varName = fileNameToVar(dm.fileName)
    lines.push(`import ${varName} from './data/${dm.fileName}'`)
  }
  lines.push('')

  // Inline minimal runtime classes
  lines.push(RUNTIME_CODE)
  lines.push('')

  // Build registry
  lines.push('// ─── Data Registry ───')
  lines.push('')

  // Group data modules by modelId
  const modelDataMap = new Map<string, { varName: string; locale: string | null }[]>()
  for (const dm of dataModules) {
    const { modelId, locale } = parseDataFileName(dm.fileName)
    if (!modelDataMap.has(modelId)) modelDataMap.set(modelId, [])
    modelDataMap.get(modelId)!.push({ varName: fileNameToVar(dm.fileName), locale })
  }

  // Create factory functions for each kind
  const collections = models.filter(m => m.kind === 'collection')
  const singletons = models.filter(m => m.kind === 'singleton')
  const dictionaries = models.filter(m => m.kind === 'dictionary')
  const documents = models.filter(m => m.kind === 'document')

  // query() function
  if (collections.length > 0) {
    lines.push('const _collectionRegistry = {')
    for (const m of collections) {
      const entries = modelDataMap.get(m.id) ?? []
      lines.push(`  '${m.id}': new Map([`)
      for (const e of entries) {
        const localeKey = e.locale ?? '_default'
        lines.push(`    ['${localeKey}', ${e.varName}],`)
      }
      lines.push('  ]),')
    }
    lines.push('}')
    lines.push('')
    lines.push('export function query(model) {')
    lines.push('  const data = _collectionRegistry[model]')
    lines.push('  if (!data) throw new Error(`Unknown collection model: "${model}"`)')
    lines.push('  return new QueryBuilder(data)')
    lines.push('}')
    lines.push('')
  }

  // singleton() function
  if (singletons.length > 0) {
    lines.push('const _singletonRegistry = {')
    for (const m of singletons) {
      const entries = modelDataMap.get(m.id) ?? []
      lines.push(`  '${m.id}': new Map([`)
      for (const e of entries) {
        const localeKey = e.locale ?? '_default'
        lines.push(`    ['${localeKey}', ${e.varName}],`)
      }
      lines.push('  ]),')
    }
    lines.push('}')
    lines.push('')
    lines.push('export function singleton(model) {')
    lines.push('  const data = _singletonRegistry[model]')
    lines.push('  if (!data) throw new Error(`Unknown singleton model: "${model}"`)')
    lines.push('  return new SingletonAccessor(data)')
    lines.push('}')
    lines.push('')
  }

  // dictionary() function
  if (dictionaries.length > 0) {
    lines.push('const _dictionaryRegistry = {')
    for (const m of dictionaries) {
      const entries = modelDataMap.get(m.id) ?? []
      lines.push(`  '${m.id}': new Map([`)
      for (const e of entries) {
        const localeKey = e.locale ?? '_default'
        lines.push(`    ['${localeKey}', ${e.varName}],`)
      }
      lines.push('  ]),')
    }
    lines.push('}')
    lines.push('')
    lines.push('export function dictionary(model) {')
    lines.push('  const data = _dictionaryRegistry[model]')
    lines.push('  if (!data) throw new Error(`Unknown dictionary model: "${model}"`)')
    lines.push('  return new DictionaryAccessor(data)')
    lines.push('}')
    lines.push('')
  }

  // document() function
  if (documents.length > 0) {
    // Group document data modules by model+locale and merge into arrays
    for (const m of documents) {
      const entries = modelDataMap.get(m.id) ?? []
      // Group entries by locale
      const byLocale = new Map<string, string[]>()
      for (const e of entries) {
        const localeKey = e.locale ?? '_default'
        if (!byLocale.has(localeKey)) byLocale.set(localeKey, [])
        byLocale.get(localeKey)!.push(e.varName)
      }
      lines.push(`const _doc_${m.id.replace(/-/g, '_')} = new Map([`)
      for (const [localeKey, varNames] of byLocale) {
        lines.push(`  ['${localeKey}', [${varNames.join(', ')}]],`)
      }
      lines.push('])')
    }
    lines.push('')
    lines.push('const _documentRegistry = {')
    for (const m of documents) {
      lines.push(`  '${m.id}': _doc_${m.id.replace(/-/g, '_')},`)
    }
    lines.push('}')
    lines.push('')
    lines.push('export function document(model) {')
    lines.push('  const data = _documentRegistry[model]')
    lines.push('  if (!data) throw new Error(`Unknown document model: "${model}"`)')
    lines.push('  return new DocumentQuery(data)')
    lines.push('}')
    lines.push('')
  }

  return lines.join('\n') + '\n'
}

export function emitCjsWrapper(models: ModelDefinition[]): string {
  const exports: string[] = []
  if (models.some(m => m.kind === 'collection')) exports.push('query')
  if (models.some(m => m.kind === 'singleton')) exports.push('singleton')
  if (models.some(m => m.kind === 'dictionary')) exports.push('dictionary')
  if (models.some(m => m.kind === 'document')) exports.push('document')

  return `// Auto-generated CJS proxy — delegates to ESM via dynamic import()
// Usage: const { query } = await import('./.contentrain/client/index.mjs')
// Or:    const client = await require('./index.cjs').init()
'use strict'
let _promise
module.exports.init = function() {
  if (!_promise) _promise = import('./index.mjs').then(function(m) {
${exports.map(e => `    module.exports.${e} = m.${e}`).join('\n')}
    return module.exports
  })
  return _promise
}
`
}

function fileNameToVar(fileName: string): string {
  // blog-post.en.mjs → _blogPostEn
  const base = fileName.replace('.mjs', '')
  const parts = base.split(/[-.]/)
  return '_' + parts.map((p, i) => i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)).join('')
}

function parseDataFileName(fileName: string): { modelId: string; locale: string | null } {
  const base = fileName.replace('.mjs', '')

  // Document files use "modelId--slug.locale" or "modelId--slug" format
  // Extract modelId from before "--", ignore slug part
  let nameForLocale = base
  if (base.includes('--')) {
    nameForLocale = base // locale is still the last dot-segment
  }

  // Extract locale from last dot-segment (e.g., "blog-post.en" → locale "en")
  const parts = nameForLocale.split('.')
  let locale: string | null = null
  let nameWithoutLocale = nameForLocale
  if (parts.length >= 2) {
    const possibleLocale = parts[parts.length - 1]!
    if (possibleLocale.length === 2 || possibleLocale.includes('-')) {
      locale = possibleLocale
      nameWithoutLocale = parts.slice(0, -1).join('.')
    }
  }

  // Extract modelId: if "--" present, it's the part before "--"
  const modelId = nameWithoutLocale.includes('--')
    ? nameWithoutLocale.split('--')[0]!
    : nameWithoutLocale

  return { modelId, locale }
}

// Inlined runtime code — zero dependencies
const RUNTIME_CODE = `
// ─── Runtime Classes ───

class QueryBuilder {
  constructor(data) { this._data = data; this._filters = []; this._sortField = null; this._sortOrder = 'asc'; this._limit = null; this._offset = 0; this._locale = null; }
  locale(lang) { this._locale = lang; return this; }
  where(field, value) { this._filters.push(item => { const v = item[field]; return Array.isArray(v) ? v.includes(value) : v === value; }); return this; }
  sort(field, order = 'asc') { this._sortField = field; this._sortOrder = order; return this; }
  limit(n) { this._limit = n; return this; }
  offset(n) { this._offset = n; return this; }
  all() {
    let items = this._locale ? [...(this._data.get(this._locale) ?? [])] : [...(this._data.get(this._data.keys().next().value) ?? [])];
    for (const f of this._filters) items = items.filter(f);
    if (this._sortField) { const sf = this._sortField; const d = this._sortOrder === 'asc' ? 1 : -1; items.sort((a, b) => { const va = a[sf], vb = b[sf]; if (va == null && vb == null) return 0; if (va == null) return d; if (vb == null) return -d; return va < vb ? -d : va > vb ? d : 0; }); }
    if (this._offset > 0 || this._limit !== null) { const end = this._limit !== null ? this._offset + this._limit : undefined; items = items.slice(this._offset, end); }
    return items;
  }
  first() { return this.all()[0]; }
}

class SingletonAccessor {
  constructor(data) { this._data = data; this._locale = null; }
  locale(lang) { this._locale = lang; return this; }
  get() {
    const key = this._locale ?? this._data.keys().next().value;
    const d = this._data.get(key);
    if (!d) throw new Error(\`No data for locale "\${key}"\`);
    return d;
  }
}

class DictionaryAccessor {
  constructor(data) { this._data = data; this._locale = null; }
  locale(lang) { this._locale = lang; return this; }
  get(key) {
    const loc = this._locale ?? this._data.keys().next().value;
    const dict = this._data.get(loc) ?? {};
    return key !== undefined ? dict[key] : dict;
  }
}

class DocumentQuery {
  constructor(data) { this._data = data; this._filters = []; this._locale = null; }
  locale(lang) { this._locale = lang; return this; }
  where(field, value) { this._filters.push(item => item[field] === value); return this; }
  bySlug(slug) { const items = this._resolveData(); return items.find(item => item.slug === slug); }
  first() { return this.all()[0]; }
  all() { let items = this._resolveData(); for (const f of this._filters) items = items.filter(f); return items; }
  _resolveData() { const key = this._locale ?? this._data.keys().next().value; return [...(this._data.get(key) ?? [])]; }
}
`.trim()
