import type { ModelDefinition, FieldDef } from '@contentrain/types'

export function emitTypes(models: ModelDefinition[]): string {
  const lines: string[] = [
    '/* eslint-disable */',
    '/* oxlint-disable */',
    '// Auto-generated by @contentrain/query — do not edit manually',
    '// Re-generate with: npx contentrain-query generate',
    '',
    "export type ContentStatus = 'draft' | 'published' | 'in_review' | 'rejected' | 'archived'",
    '',
  ]

  // Model interfaces
  for (const model of models) {
    if (model.kind === 'dictionary') {
      lines.push(`export type ${kebabToPascal(model.id)} = Record<string, string>`)
    } else {
      lines.push(`export interface ${kebabToPascal(model.id)} {`)
      // System fields by kind
      if (model.kind === 'collection') {
        lines.push('  id: string')
      }
      if (model.kind === 'document') {
        lines.push('  slug: string')
        lines.push('  content: string')
      }
      // User fields
      if (model.fields) {
        for (const [name, field] of Object.entries(model.fields)) {
          const tsType = fieldToTS(field)
          const optional = field.required ? '' : '?'
          lines.push(`  ${name}${optional}: ${tsType}`)
        }
      }
      lines.push('}')
    }
    lines.push('')
  }

  // Query interfaces
  lines.push(`export interface QueryBuilder<T> {
  locale(lang: string): QueryBuilder<T>
  where<K extends keyof T>(field: K, value: T[K]): QueryBuilder<T>
  sort<K extends keyof T>(field: K, order?: 'asc' | 'desc'): QueryBuilder<T>
  limit(n: number): QueryBuilder<T>
  offset(n: number): QueryBuilder<T>
  include(...fields: string[]): QueryBuilder<T>
  first(): T | undefined
  all(): T[]
}`)
  lines.push('')

  lines.push(`export interface SingletonAccessor<T> {
  locale(lang: string): SingletonAccessor<T>
  include(...fields: string[]): SingletonAccessor<T>
  get(): T
}`)
  lines.push('')

  lines.push(`export interface DictionaryAccessor {
  locale(lang: string): DictionaryAccessor
  get(): Record<string, string>
  get(key: string): string | undefined
}`)
  lines.push('')

  lines.push(`export interface DocumentQuery<T> {
  locale(lang: string): DocumentQuery<T>
  where<K extends keyof T>(field: K, value: T[K]): DocumentQuery<T>
  include(...fields: string[]): DocumentQuery<T>
  bySlug(slug: string): T | undefined
  first(): T | undefined
  all(): T[]
}`)
  lines.push('')

  // Overloaded entry points
  const collections = models.filter(m => m.kind === 'collection')
  const singletons = models.filter(m => m.kind === 'singleton')
  const dictionaries = models.filter(m => m.kind === 'dictionary')
  const documents = models.filter(m => m.kind === 'document')

  // query() overloads
  for (const m of collections) {
    lines.push(`export declare function query(model: '${m.id}'): QueryBuilder<${kebabToPascal(m.id)}>`)
  }
  lines.push('export declare function query(model: string): QueryBuilder<Record<string, unknown>>')
  lines.push('')

  // singleton() overloads
  for (const m of singletons) {
    lines.push(`export declare function singleton(model: '${m.id}'): SingletonAccessor<${kebabToPascal(m.id)}>`)
  }
  lines.push('export declare function singleton(model: string): SingletonAccessor<Record<string, unknown>>')
  lines.push('')

  // dictionary() overloads
  for (const m of dictionaries) {
    lines.push(`export declare function dictionary(model: '${m.id}'): DictionaryAccessor`)
  }
  lines.push('export declare function dictionary(model: string): DictionaryAccessor')
  lines.push('')

  // document() overloads
  for (const m of documents) {
    lines.push(`export declare function document(model: '${m.id}'): DocumentQuery<${kebabToPascal(m.id)}>`)
  }
  lines.push('export declare function document(model: string): DocumentQuery<Record<string, unknown>>')
  lines.push('')

  // Typed client interface
  lines.push('export interface ContentrainClient {')
  for (const m of collections) {
    lines.push(`  query(model: '${m.id}'): QueryBuilder<${kebabToPascal(m.id)}>`)
  }
  lines.push('  query(model: string): QueryBuilder<Record<string, unknown>>')
  for (const m of singletons) {
    lines.push(`  singleton(model: '${m.id}'): SingletonAccessor<${kebabToPascal(m.id)}>`)
  }
  lines.push('  singleton(model: string): SingletonAccessor<Record<string, unknown>>')
  for (const m of dictionaries) {
    lines.push(`  dictionary(model: '${m.id}'): DictionaryAccessor`)
  }
  lines.push('  dictionary(model: string): DictionaryAccessor')
  for (const m of documents) {
    lines.push(`  document(model: '${m.id}'): DocumentQuery<${kebabToPascal(m.id)}>`)
  }
  lines.push('  document(model: string): DocumentQuery<Record<string, unknown>>')
  lines.push('}')
  lines.push('')
  lines.push('export declare function createContentrainClient(): ContentrainClient')
  lines.push('')

  return lines.join('\n') + '\n'
}

function fieldToTS(field: FieldDef): string {
  switch (field.type) {
    case 'string': case 'text': case 'email': case 'url': case 'slug':
    case 'color': case 'phone': case 'code': case 'icon':
    case 'markdown': case 'richtext':
    case 'date': case 'datetime':
    case 'image': case 'video': case 'file':
    case 'relation':
      if (Array.isArray(field.model) && field.model.length > 1) {
        const union = field.model.map(m => `'${m}'`).join(' | ')
        return `{ model: ${union}; ref: string }`
      }
      return 'string'

    case 'relations':
      if (Array.isArray(field.model) && field.model.length > 1) {
        const union = field.model.map(m => `'${m}'`).join(' | ')
        return `Array<{ model: ${union}; ref: string }>`
      }
      return 'string[]'

    case 'number': case 'integer': case 'decimal': case 'percent': case 'rating':
      return 'number'

    case 'boolean':
      return 'boolean'

    case 'select':
      if (field.options && field.options.length > 0) {
        return field.options.map(o => `'${o}'`).join(' | ')
      }
      return 'string'

    case 'array':
      if (field.items) {
        if (typeof field.items === 'string') {
          return `${primitiveToTS(field.items)}[]`
        }
        // items is a FieldDef
        return `${fieldToTS(field.items)}[]`
      }
      return 'unknown[]'

    case 'object':
      if (field.fields) {
        const entries = Object.entries(field.fields)
          .map(([k, v]) => `${k}${v.required ? '' : '?'}: ${fieldToTS(v)}`)
          .join('; ')
        return `{ ${entries} }`
      }
      return 'Record<string, unknown>'

    default:
      return 'unknown'
  }
}

function primitiveToTS(type: string): string {
  if (['string', 'text', 'email', 'url', 'slug', 'color', 'phone', 'code', 'icon',
       'markdown', 'richtext', 'date', 'datetime', 'image', 'video', 'file', 'relation'].includes(type)) {
    return 'string'
  }
  if (['number', 'integer', 'decimal', 'percent', 'rating'].includes(type)) {
    return 'number'
  }
  if (type === 'boolean') return 'boolean'
  return 'unknown'
}

function kebabToPascal(s: string): string {
  return s.split('-').map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('')
}
