#!/usr/bin/env node
/**
 * build-rules.ts — Merge shared rules into IDE-specific bundles
 *
 * Reads all rules/shared/*.md files and concatenates them into
 * IDE-specific rule files with appropriate formatting.
 *
 * Usage: npx tsx scripts/build-rules.ts
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const SHARED_DIR = join(ROOT, 'shared')

// Content quality rules come first, then architecture rules
const RULE_ORDER = [
  // Content Quality
  'content-quality.md',
  'seo-rules.md',
  'i18n-quality.md',
  'accessibility-rules.md',
  'security-rules.md',
  'media-rules.md',
  // Architecture
  'content-conventions.md',
  'schema-rules.md',
  'mcp-usage.md',
  'workflow-rules.md',
  'normalize-rules.md',
]

async function readSharedRules(): Promise<{ name: string; content: string }[]> {
  const results: { name: string; content: string }[] = []

  for (const fileName of RULE_ORDER) {
    const filePath = join(SHARED_DIR, fileName)
    try {
      const content = await readFile(filePath, 'utf-8')
      results.push({ name: fileName, content: content.trim() })
    } catch {
      console.warn(`Warning: ${fileName} not found, skipping`)
    }
  }

  return results
}

function buildClaudeCode(rules: { name: string; content: string }[]): string {
  const lines = [
    '# Contentrain — AI Content Governance Rules',
    '',
    '> Auto-generated by @contentrain/rules. Do not edit manually.',
    '> Regenerate with: `npx tsx scripts/build-rules.ts`',
    '',
    '---',
    '',
  ]

  for (const rule of rules) {
    lines.push(rule.content)
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  return lines.join('\n')
}

function buildCursor(rules: { name: string; content: string }[]): string {
  // Cursor uses .cursorrules — same markdown content, different header
  const lines = [
    '# Contentrain Rules',
    '',
    'These rules govern content creation and management in Contentrain projects.',
    '',
  ]

  for (const rule of rules) {
    lines.push(rule.content)
    lines.push('')
  }

  return lines.join('\n')
}

function buildGeneric(rules: { name: string; content: string }[]): string {
  // Universal format — works with any AI agent
  const lines = [
    '# Contentrain — Content Governance Rules for AI Agents',
    '',
    'These rules apply when working with Contentrain projects (.contentrain/ directory).',
    'Follow these rules for content creation, schema management, and workflow.',
    '',
    '---',
    '',
  ]

  for (const rule of rules) {
    lines.push(rule.content)
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  return lines.join('\n')
}

async function main() {
  const rules = await readSharedRules()

  if (rules.length === 0) {
    console.error('No shared rules found!')
    process.exit(1)
  }

  console.log(`Read ${rules.length} shared rule files`)

  const outputs = [
    { dir: 'ide/claude-code', file: 'contentrain.md', content: buildClaudeCode(rules) },
    { dir: 'ide/cursor', file: 'contentrain.cursorrules', content: buildCursor(rules) },
    { dir: 'ide/windsurf', file: 'contentrain.windsurfrules', content: buildGeneric(rules) },
    { dir: 'ide/generic', file: 'contentrain.md', content: buildGeneric(rules) },
  ]

  for (const output of outputs) {
    const dirPath = join(ROOT, output.dir)
    await mkdir(dirPath, { recursive: true })
    const filePath = join(dirPath, output.file)
    await writeFile(filePath, output.content, 'utf-8')
    console.log(`  Written: ${output.dir}/${output.file}`)
  }

  console.log('Done.')
}

main()
