import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { generate } from '../../src/generator/generate.js'
import { access, cp, mkdtemp, readFile, rm, unlink, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { tmpdir } from 'node:os'
import { createRequire } from 'node:module'

const FIXTURE = join(import.meta.dirname, '../fixtures/basic-blog')
const CLIENT_DIR = join(FIXTURE, '.contentrain', 'client')

describe('generate (integration)', () => {
  beforeEach(async () => {
    // Clean generated output before each test
    await rm(CLIENT_DIR, { recursive: true, force: true })
  })

  afterEach(async () => {
    await rm(CLIENT_DIR, { recursive: true, force: true })
  })

  it('generates all output files and returns correct result', async () => {
    const result = await generate({ projectRoot: FIXTURE })

    // Check result counts — 6 models: author, blog-article, blog-post, error-messages, hero, tag
    expect(result.typesCount).toBe(6)
    expect(result.dataModulesCount).toBeGreaterThanOrEqual(10)
    expect(result.generatedFiles).toContain('index.d.ts')
    expect(result.generatedFiles).toContain('index.mjs')
    expect(result.generatedFiles).toContain('index.cjs')
    expect(result.generatedFiles.some(f => f.startsWith('data/'))).toBe(true)
  })

  it('generates valid TypeScript declarations', async () => {
    await generate({ projectRoot: FIXTURE })

    const types = await readFile(join(CLIENT_DIR, 'index.d.ts'), 'utf-8')
    expect(types).toContain('// Auto-generated by @contentrain/query')
    // Collection
    expect(types).toContain('export interface BlogPost')
    expect(types).toContain('id: string')
    // Singleton
    expect(types).toContain('export interface Hero')
    // Dictionary
    expect(types).toContain('export type ErrorMessages = Record<string, string>')
    // Document
    expect(types).toContain('export interface BlogArticle')
    expect(types).toContain('slug: string')
    expect(types).toContain('content: string')
    // Relation model types
    expect(types).toContain('export interface Author')
    expect(types).toContain('export interface Tag')
    // Query interfaces with include()
    expect(types).toContain('export interface QueryBuilder<T>')
    expect(types).toContain('include(...fields: string[]): QueryBuilder<T>')
    expect(types).toContain('export interface SingletonAccessor<T>')
    expect(types).toContain('export interface DictionaryAccessor')
    expect(types).toContain('export interface DocumentQuery<T>')
    expect(types).toContain('include(...fields: string[]): DocumentQuery<T>')
    // Overloaded entry points
    expect(types).toContain("export declare function query(model: 'blog-post')")
    expect(types).toContain("export declare function query(model: 'author')")
    expect(types).toContain("export declare function query(model: 'tag')")
    expect(types).toContain("export declare function singleton(model: 'hero')")
    expect(types).toContain("export declare function dictionary(model: 'error-messages')")
    expect(types).toContain("export declare function document(model: 'blog-article')")
  })

  it('generates ESM runtime with data imports and registries', async () => {
    await generate({ projectRoot: FIXTURE })

    const esm = await readFile(join(CLIENT_DIR, 'index.mjs'), 'utf-8')
    expect(esm).toContain('// Auto-generated by @contentrain/query')
    // Data imports
    expect(esm).toContain("from './data/blog-post.en.mjs'")
    expect(esm).toContain("from './data/hero.en.mjs'")
    expect(esm).toContain("from './data/error-messages.en.mjs'")
    expect(esm).toContain("from './data/author.mjs'")
    expect(esm).toContain("from './data/tag.mjs'")
    // Runtime classes
    expect(esm).toContain('class QueryBuilder')
    expect(esm).toContain('class SingletonAccessor')
    expect(esm).toContain('class DictionaryAccessor')
    expect(esm).toContain('class DocumentQuery')
    // Factory functions
    expect(esm).toContain('export function query(')
    expect(esm).toContain('export function singleton(')
    expect(esm).toContain('export function dictionary(')
    expect(esm).toContain('export function document(')
    // Relation metadata
    expect(esm).toContain('_relationMeta')
    expect(esm).toContain('_resolveEntry')
  })

  it('generates CJS wrapper without top-level await', async () => {
    await generate({ projectRoot: FIXTURE })

    const cjs = await readFile(join(CLIENT_DIR, 'index.cjs'), 'utf-8')
    expect(cjs).toContain("'use strict'")
    expect(cjs).toContain("import('./index.mjs')")
    // Code lines (not comments) should not contain top-level await
    const codeLines = cjs.split('\n').filter((l: string) => !l.trimStart().startsWith('//'))
    expect(codeLines.join('\n')).not.toContain('await ')
    expect(cjs).toContain('module.exports.init')
  })

  it('generates data modules with canonical JSON', async () => {
    await generate({ projectRoot: FIXTURE })

    // Collection data module
    const collectionData = await readFile(join(CLIENT_DIR, 'data', 'blog-post.en.mjs'), 'utf-8')
    expect(collectionData).toContain('export default')
    // Should be an array (object-map transformed)
    const jsonStr = collectionData.replace('export default ', '').trim()
    const parsed = JSON.parse(jsonStr) as Array<{ id: string }>
    expect(Array.isArray(parsed)).toBe(true)
    expect(parsed.length).toBe(3)
    // Sorted by ID
    const ids = parsed.map(e => e.id)
    expect(ids).toEqual([...ids].toSorted())
    // Canonical JSON: keys sorted
    const firstEntry = parsed[0]!
    const keys = Object.keys(firstEntry)
    expect(keys).toEqual([...keys].toSorted())

    // Singleton data module
    const singletonData = await readFile(join(CLIENT_DIR, 'data', 'hero.en.mjs'), 'utf-8')
    expect(singletonData).toContain('export default')
    expect(singletonData).toContain('"title"')

    // Dictionary data module
    const dictData = await readFile(join(CLIENT_DIR, 'data', 'error-messages.en.mjs'), 'utf-8')
    expect(dictData).toContain('export default')
  })

  it('generates document data modules with slug prefix', async () => {
    await generate({ projectRoot: FIXTURE })

    // Document data modules use "modelId--slug.locale.mjs" naming
    const docData = await readFile(join(CLIENT_DIR, 'data', 'blog-article--welcome-post.en.mjs'), 'utf-8')
    expect(docData).toContain('export default')
    expect(docData).toContain('"slug": "welcome-post"')
    expect(docData).toContain('"content"')
    // Canonical JSON: keys sorted
    const jsonStr = docData.replace('export default ', '').trim()
    const parsed = JSON.parse(jsonStr)
    const keys = Object.keys(parsed)
    expect(keys).toEqual([...keys].toSorted())
  })

  it('document registry aggregates multiple slugs per locale', async () => {
    await generate({ projectRoot: FIXTURE })

    const esm = await readFile(join(CLIENT_DIR, 'index.mjs'), 'utf-8')
    // Both welcome-post and design-tips should be in the same en array
    expect(esm).toContain('_blogArticleWelcomePostEn')
    expect(esm).toContain('_blogArticleDesignTipsEn')
    // They should be in the same Map entry for 'en'
    expect(esm).toMatch(/\['en',\s*\[.*_blogArticle.*_blogArticle.*\]/)
  })

  it('generates relation metadata for blog-post model', async () => {
    await generate({ projectRoot: FIXTURE })

    const esm = await readFile(join(CLIENT_DIR, 'index.mjs'), 'utf-8')
    // blog-post has author (relation) and tags (relations)
    expect(esm).toContain("'author': { target: 'author', multi: false }")
    expect(esm).toContain("'tags': { target: 'tag', multi: true }")
    // Factory should pass relation meta to QueryBuilder
    expect(esm).toContain('_relationMeta[model], _resolveEntry')
  })

  it('is idempotent — running twice produces same output', async () => {
    const result1 = await generate({ projectRoot: FIXTURE })
    const types1 = await readFile(join(CLIENT_DIR, 'index.d.ts'), 'utf-8')
    const esm1 = await readFile(join(CLIENT_DIR, 'index.mjs'), 'utf-8')

    const result2 = await generate({ projectRoot: FIXTURE })
    const types2 = await readFile(join(CLIENT_DIR, 'index.d.ts'), 'utf-8')
    const esm2 = await readFile(join(CLIENT_DIR, 'index.mjs'), 'utf-8')

    expect(result1.typesCount).toBe(result2.typesCount)
    expect(result1.dataModulesCount).toBe(result2.dataModulesCount)
    expect(types1).toBe(types2)
    expect(esm1).toBe(esm2)
  })

  it('uses config.locales.default when locale() is omitted', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-default-locale-'))

    try {
      await cp(FIXTURE, tempRoot, { recursive: true })

      const configPath = join(tempRoot, '.contentrain', 'config.json')
      const rawConfig = JSON.parse(await readFile(configPath, 'utf-8')) as Record<string, unknown>
      rawConfig['locales'] = { default: 'en', supported: ['tr', 'en'] }
      await writeFile(configPath, JSON.stringify(rawConfig, null, 2) + '\n', 'utf-8')

      await generate({ projectRoot: tempRoot })

      const clientPath = pathToFileURL(join(tempRoot, '.contentrain', 'client', 'index.mjs')).href
      const client = await import(clientPath)

      expect(client.singleton('hero').get().title).toBe('Welcome to Contentrain')
      expect(client.query('blog-post').first().title).toBe('Getting Started with Contentrain')
      // document().first() returns alphabetically first slug — 'design-tips' before 'welcome-post'
      expect(client.document('blog-article').first().title).toBe('Design Tips')
    } finally {
      await rm(tempRoot, { recursive: true, force: true })
    }
  })

  it('removes stale data modules when source files disappear', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-stale-client-'))

    try {
      await cp(FIXTURE, tempRoot, { recursive: true })

      await generate({ projectRoot: tempRoot })

      const staleModulePath = join(tempRoot, '.contentrain', 'client', 'data', 'blog-post.tr.mjs')
      await access(staleModulePath)

      await unlink(join(tempRoot, '.contentrain', 'content', 'blog', 'blog-post', 'tr.json'))
      await generate({ projectRoot: tempRoot })

      await expect(access(staleModulePath)).rejects.toThrow()
    } finally {
      await rm(tempRoot, { recursive: true, force: true })
    }
  })

  it('exposes usable query exports via CommonJS require + init()', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-cjs-'))

    try {
      await cp(FIXTURE, tempRoot, { recursive: true })
      await generate({ projectRoot: tempRoot })

      const require = createRequire(import.meta.url)
      const cjs = require(join(tempRoot, '.contentrain', 'client', 'index.cjs')) as Record<string, unknown>

      // CJS wrapper requires init() — ESM→CJS bridge is async
      expect(typeof cjs.init).toBe('function')
      const client = await (cjs.init as () => Promise<Record<string, unknown>>)()

      expect(typeof client.query).toBe('function')
      expect(typeof client.singleton).toBe('function')
    } finally {
      await rm(tempRoot, { recursive: true, force: true })
    }
  })
})
