import { describe, it, expect, beforeAll, beforeEach, afterAll } from 'vitest'
import { generate } from '../../src/generator/generate.js'
import { access, cp, mkdtemp, readFile, rm, unlink, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { tmpdir } from 'node:os'
import { createRequire } from 'node:module'

const FIXTURE = join(import.meta.dirname, '../fixtures/basic-blog')

describe('generate (integration)', () => {
  // Use a temp copy of the fixture to avoid mutating the shared fixture directory,
  // which causes race conditions when parallel test files cp from it concurrently.
  let projectRoot: string
  let clientDir: string

  beforeAll(async () => {
    projectRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-gen-'))
    await cp(FIXTURE, projectRoot, { recursive: true })
    clientDir = join(projectRoot, '.contentrain', 'client')
  })

  beforeEach(async () => {
    // Clean generated output before each test
    await rm(clientDir, { recursive: true, force: true })
  })

  afterAll(async () => {
    await rm(projectRoot, { recursive: true, force: true })
  })

  it('generates all output files and returns correct result', async () => {
    const result = await generate({ projectRoot })

    // Check result counts — 6 models: author, blog-article, blog-post, error-messages, hero, tag
    expect(result.typesCount).toBe(6)
    expect(result.dataModulesCount).toBeGreaterThanOrEqual(10)
    expect(result.generatedFiles).toContain('index.d.ts')
    expect(result.generatedFiles).toContain('index.mjs')
    expect(result.generatedFiles).toContain('index.cjs')
    expect(result.generatedFiles.some(f => f.startsWith('data/'))).toBe(true)
  })

  it('generates valid TypeScript declarations', async () => {
    await generate({ projectRoot })

    const types = await readFile(join(clientDir, 'index.d.ts'), 'utf-8')
    expect(types).toContain('// Auto-generated by @contentrain/query')
    // Collection
    expect(types).toContain('export interface BlogPost')
    expect(types).toContain('id: string')
    // Singleton
    expect(types).toContain('export interface Hero')
    // Dictionary
    expect(types).toContain('export type ErrorMessages = Record<string, string>')
    // Document
    expect(types).toContain('export interface BlogArticle')
    expect(types).toContain('slug: string')
    expect(types).toContain('body: string')
    // Relation model types
    expect(types).toContain('export interface Author')
    expect(types).toContain('export interface Tag')
    // Query interfaces with include()
    expect(types).toContain('export interface QueryBuilder<T>')
    expect(types).toContain('include<K extends keyof T & string>(...fields: K[]): QueryBuilder<T>')
    expect(types).toContain('export interface SingletonAccessor<T>')
    expect(types).toContain('export interface DictionaryAccessor')
    expect(types).toContain('export interface DocumentQuery<T>')
    expect(types).toContain('include<K extends keyof T & string>(...fields: K[]): DocumentQuery<T>')
    // Overloaded entry points — typed overloads
    expect(types).toContain("export declare function query(model: 'blog-post'): QueryBuilder<BlogPost>")
    expect(types).toContain("export declare function query(model: 'author'): QueryBuilder<Author>")
    expect(types).toContain("export declare function query(model: 'tag'): QueryBuilder<Tag>")
    expect(types).toContain("export declare function singleton(model: 'hero'): SingletonAccessor<Hero>")
    expect(types).toContain("export declare function dictionary(model: 'error-messages'): DictionaryAccessor")
    expect(types).toContain("export declare function document(model: 'blog-article'): DocumentQuery<BlogArticle>")
    // Fallback overloads
    expect(types).toContain('export declare function query(model: string): QueryBuilder<Record<string, unknown>>')
    expect(types).toContain('export declare function singleton(model: string): SingletonAccessor<Record<string, unknown>>')
    expect(types).toContain('export declare function dictionary(model: string): DictionaryAccessor')
    expect(types).toContain('export declare function document(model: string): DocumentQuery<Record<string, unknown>>')
    // Typed client interface
    expect(types).toContain('export interface ContentrainClient {')
    expect(types).toContain('export declare function createContentrainClient(): ContentrainClient')
  })

  it('generates ESM runtime with data imports and registries', async () => {
    await generate({ projectRoot })

    const esm = await readFile(join(clientDir, 'index.mjs'), 'utf-8')
    expect(esm).toContain('// Auto-generated by @contentrain/query')
    // Data imports
    expect(esm).toContain("from './data/blog-post.en.mjs'")
    expect(esm).toContain("from './data/hero.en.mjs'")
    expect(esm).toContain("from './data/error-messages.en.mjs'")
    expect(esm).toContain("from './data/author.mjs'")
    expect(esm).toContain("from './data/tag.mjs'")
    // Runtime classes
    expect(esm).toContain('class QueryBuilder')
    expect(esm).toContain('class SingletonAccessor')
    expect(esm).toContain('class DictionaryAccessor')
    expect(esm).toContain('class DocumentQuery')
    // Factory functions
    expect(esm).toContain('export function query(')
    expect(esm).toContain('export function singleton(')
    expect(esm).toContain('export function dictionary(')
    expect(esm).toContain('export function document(')
    // Relation metadata
    expect(esm).toContain('_relationMeta')
    expect(esm).toContain('_resolveEntry')
  })

  it('generates CJS wrapper without top-level await', async () => {
    await generate({ projectRoot })

    const cjs = await readFile(join(clientDir, 'index.cjs'), 'utf-8')
    expect(cjs).toContain("'use strict'")
    expect(cjs).toContain("import('./index.mjs')")
    // Code lines (not comments) should not contain top-level await
    const codeLines = cjs.split('\n').filter((l: string) => !l.trimStart().startsWith('//'))
    expect(codeLines.join('\n')).not.toContain('await ')
    expect(cjs).toContain('module.exports.init')
  })

  it('generates data modules with canonical JSON', async () => {
    await generate({ projectRoot })

    // Collection data module
    const collectionData = await readFile(join(clientDir, 'data', 'blog-post.en.mjs'), 'utf-8')
    expect(collectionData).toContain('export default')
    // Should be an array (object-map transformed)
    const jsonStr = collectionData.replace('export default ', '').trim()
    const parsed = JSON.parse(jsonStr) as Array<{ id: string }>
    expect(Array.isArray(parsed)).toBe(true)
    expect(parsed.length).toBe(3)
    // Sorted by ID
    const ids = parsed.map(e => e.id)
    expect(ids).toEqual([...ids].toSorted())
    // Canonical JSON: keys sorted
    const firstEntry = parsed[0]!
    const keys = Object.keys(firstEntry)
    expect(keys).toEqual([...keys].toSorted())

    // Singleton data module
    const singletonData = await readFile(join(clientDir, 'data', 'hero.en.mjs'), 'utf-8')
    expect(singletonData).toContain('export default')
    expect(singletonData).toContain('"title"')

    // Dictionary data module
    const dictData = await readFile(join(clientDir, 'data', 'error-messages.en.mjs'), 'utf-8')
    expect(dictData).toContain('export default')
  })

  it('generates document data modules with slug prefix', async () => {
    await generate({ projectRoot })

    // Document data modules use "modelId--slug.locale.mjs" naming
    const docData = await readFile(join(clientDir, 'data', 'blog-article--welcome-post.en.mjs'), 'utf-8')
    expect(docData).toContain('export default')
    expect(docData).toContain('"slug": "welcome-post"')
    expect(docData).toContain('"body"')
    // Canonical JSON: keys sorted
    const jsonStr = docData.replace('export default ', '').trim()
    const parsed = JSON.parse(jsonStr)
    const keys = Object.keys(parsed)
    expect(keys).toEqual([...keys].toSorted())
  })

  it('document registry aggregates multiple slugs per locale', async () => {
    await generate({ projectRoot })

    const esm = await readFile(join(clientDir, 'index.mjs'), 'utf-8')
    // Both welcome-post and design-tips should be in the same en array
    expect(esm).toContain('_blogArticleWelcomePostEn')
    expect(esm).toContain('_blogArticleDesignTipsEn')
    // They should be in the same Map entry for 'en'
    expect(esm).toMatch(/\['en',\s*\[.*_blogArticle.*_blogArticle.*\]/)
  })

  it('generates relation metadata for blog-post model', async () => {
    await generate({ projectRoot })

    const esm = await readFile(join(clientDir, 'index.mjs'), 'utf-8')
    // blog-post has author (relation) and tags (relations)
    expect(esm).toContain("'author': { target: 'author', multi: false }")
    expect(esm).toContain("'tags': { target: 'tag', multi: true }")
    // Factory should pass relation meta to QueryBuilder
    expect(esm).toContain('_relationMeta[model], _resolveEntry')
  })

  it('is idempotent — running twice produces same output', async () => {
    const result1 = await generate({ projectRoot })
    const types1 = await readFile(join(clientDir, 'index.d.ts'), 'utf-8')
    const esm1 = await readFile(join(clientDir, 'index.mjs'), 'utf-8')

    const result2 = await generate({ projectRoot })
    const types2 = await readFile(join(clientDir, 'index.d.ts'), 'utf-8')
    const esm2 = await readFile(join(clientDir, 'index.mjs'), 'utf-8')

    expect(result1.typesCount).toBe(result2.typesCount)
    expect(result1.dataModulesCount).toBe(result2.dataModulesCount)
    expect(types1).toBe(types2)
    expect(esm1).toBe(esm2)
  })

  it('uses config.locales.default when locale() is omitted', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-default-locale-'))

    try {
      await cp(FIXTURE, tempRoot, { recursive: true })

      const configPath = join(tempRoot, '.contentrain', 'config.json')
      const rawConfig = JSON.parse(await readFile(configPath, 'utf-8')) as Record<string, unknown>
      rawConfig['locales'] = { default: 'en', supported: ['tr', 'en'] }
      await writeFile(configPath, JSON.stringify(rawConfig, null, 2) + '\n', 'utf-8')

      await generate({ projectRoot: tempRoot })

      const clientPath = pathToFileURL(join(tempRoot, '.contentrain', 'client', 'index.mjs')).href
      const client = await import(clientPath)

      expect(client.singleton('hero').get().title).toBe('Welcome to Contentrain')
      expect(client.query('blog-post').first().title).toBe('Getting Started with Contentrain')
      // document().first() returns alphabetically first slug — 'design-tips' before 'welcome-post'
      expect(client.document('blog-article').first().title).toBe('Design Tips')
    } finally {
      await rm(tempRoot, { recursive: true, force: true })
    }
  })

  it('removes stale data modules when source files disappear', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-stale-client-'))

    try {
      await cp(FIXTURE, tempRoot, { recursive: true })

      await generate({ projectRoot: tempRoot })

      const staleModulePath = join(tempRoot, '.contentrain', 'client', 'data', 'blog-post.tr.mjs')
      await access(staleModulePath)

      await unlink(join(tempRoot, '.contentrain', 'content', 'blog', 'blog-post', 'tr.json'))
      await generate({ projectRoot: tempRoot })

      await expect(access(staleModulePath)).rejects.toThrow()
    } finally {
      await rm(tempRoot, { recursive: true, force: true })
    }
  })

  it('interpolates dictionary params in the generated runtime (regex survives emit)', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-dict-'))
    try {
      await cp(FIXTURE, tempRoot, { recursive: true })
      // Add an interpolated value to the error-messages dictionary (en)
      const dictEn = join(tempRoot, '.contentrain', 'content', 'system', 'error-messages', 'en.json')
      const raw = JSON.parse(await readFile(dictEn, 'utf-8')) as Record<string, string>
      raw['greeting'] = 'Hello {name}, you have {count} messages'
      await writeFile(dictEn, JSON.stringify(raw, null, 2) + '\n', 'utf-8')

      await generate({ projectRoot: tempRoot })
      const clientPath = pathToFileURL(join(tempRoot, '.contentrain', 'client', 'index.mjs')).href
      const client = await import(clientPath)

      const out = client.dictionary('error-messages').get('greeting', { name: 'Ada', count: 3 })
      expect(out).toBe('Hello Ada, you have 3 messages')
      // No-params call returns the raw template untouched
      expect(client.dictionary('error-messages').get('greeting')).toBe('Hello {name}, you have {count} messages')
    } finally {
      await rm(tempRoot, { recursive: true, force: true })
    }
  })

  it('DocumentQuery.sort() orders documents in the generated runtime', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-docsort-'))
    try {
      await cp(FIXTURE, tempRoot, { recursive: true })
      await generate({ projectRoot: tempRoot })
      const clientPath = pathToFileURL(join(tempRoot, '.contentrain', 'client', 'index.mjs')).href
      const client = await import(clientPath)

      const asc = client.document('blog-article').sort('title', 'asc').all().map((d: { title: string }) => d.title)
      const desc = client.document('blog-article').sort('title', 'desc').all().map((d: { title: string }) => d.title)
      expect(asc).toEqual([...asc].toSorted())
      expect(desc).toEqual([...asc].toReversed())
    } finally {
      await rm(tempRoot, { recursive: true, force: true })
    }
  })

  it('include() resolves an i18n:false relation target from an i18n:true source', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-include-'))
    try {
      await cp(FIXTURE, tempRoot, { recursive: true })
      await generate({ projectRoot: tempRoot })
      const clientPath = pathToFileURL(join(tempRoot, '.contentrain', 'client', 'index.mjs')).href
      const client = await import(clientPath)

      // blog-post is i18n:true, author is i18n:false (stored under '_default').
      // Without an explicit .locale(): effective locale = default → must still resolve.
      const noLocale = client.query('blog-post').include('author').first()
      expect(typeof noLocale.author).toBe('object')
      expect(noLocale.author.name).toBeTruthy()

      // With an explicit .locale('en'): must also resolve the '_default' author.
      const withLocale = client.query('blog-post').locale('en').include('author').first()
      expect(typeof withLocale.author).toBe('object')
      expect(withLocale.author.name).toBeTruthy()
    } finally {
      await rm(tempRoot, { recursive: true, force: true })
    }
  })

  it('exposes usable query exports via CommonJS require + init()', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-cjs-'))

    try {
      await cp(FIXTURE, tempRoot, { recursive: true })
      await generate({ projectRoot: tempRoot })

      const require = createRequire(import.meta.url)
      const cjs = require(join(tempRoot, '.contentrain', 'client', 'index.cjs')) as Record<string, unknown>

      // CJS wrapper requires init() — ESM→CJS bridge is async
      expect(typeof cjs.init).toBe('function')
      const client = await (cjs.init as () => Promise<Record<string, unknown>>)()

      expect(typeof client.query).toBe('function')
      expect(typeof client.singleton).toBe('function')
    } finally {
      await rm(tempRoot, { recursive: true, force: true })
    }
  })

  it('bakes a working media() resolver into the client when cdnBaseUrl is set', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'contentrain-sdk-media-'))

    try {
      await cp(FIXTURE, tempRoot, { recursive: true })
      await generate({ projectRoot: tempRoot, cdnBaseUrl: 'https://cdn.test/api/cdn/v1/proj/' })

      const types = await readFile(join(tempRoot, '.contentrain', 'client', 'index.d.ts'), 'utf-8')
      expect(types).toContain('export declare function media(value: string): string')

      const clientPath = pathToFileURL(join(tempRoot, '.contentrain', 'client', 'index.mjs')).href
      const client = await import(clientPath)

      // stored path → absolute delivery URL (trailing slash on base trimmed)
      expect(client.media('media/original/a.webp')).toBe('https://cdn.test/api/cdn/v1/proj/media/original/a.webp')
      // external + already-absolute pass through untouched (idempotent)
      expect(client.media('https://images.unsplash.com/y.jpg')).toBe('https://images.unsplash.com/y.jpg')
      expect(client.media('https://cdn.test/api/cdn/v1/proj/media/original/a.webp'))
        .toBe('https://cdn.test/api/cdn/v1/proj/media/original/a.webp')
    } finally {
      await rm(tempRoot, { recursive: true, force: true })
    }
  })

  it('omits media() from the client when no CDN base is configured', async () => {
    await generate({ projectRoot })

    const types = await readFile(join(clientDir, 'index.d.ts'), 'utf-8')
    const esm = await readFile(join(clientDir, 'index.mjs'), 'utf-8')
    expect(types).not.toContain('function media(')
    expect(esm).not.toContain('export function media(')
  })
})
