import { describe, it, expect } from 'vitest'
import { emitRuntimeModule, emitCjsWrapper } from '../../src/generator/runtime-emitter.js'
import type { ModelDefinition } from '@contentrain/types'
import type { DataModule } from '../../src/generator/data-emitter.js'

const COLLECTION_MODEL: ModelDefinition = {
  id: 'blog-post', name: 'Blog Post', kind: 'collection', domain: 'blog', i18n: true,
}

const SINGLETON_MODEL: ModelDefinition = {
  id: 'hero', name: 'Hero', kind: 'singleton', domain: 'marketing', i18n: true,
}

const DICTIONARY_MODEL: ModelDefinition = {
  id: 'errors', name: 'Errors', kind: 'dictionary', domain: 'system', i18n: true,
}

const DOCUMENT_MODEL: ModelDefinition = {
  id: 'blog-article', name: 'Blog Article', kind: 'document', domain: 'blog', i18n: true,
}

describe('emitRuntimeModule', () => {
  it('generates auto-generated header', () => {
    const output = emitRuntimeModule([COLLECTION_MODEL], [
      { fileName: 'blog-post.en.mjs', content: 'export default []' },
    ])
    expect(output).toContain('// Auto-generated by @contentrain/query')
  })

  it('generates import statements for data modules', () => {
    const output = emitRuntimeModule([COLLECTION_MODEL], [
      { fileName: 'blog-post.en.mjs', content: '' },
      { fileName: 'blog-post.tr.mjs', content: '' },
    ])
    expect(output).toContain("import _blogPostEn from './data/blog-post.en.mjs'")
    expect(output).toContain("import _blogPostTr from './data/blog-post.tr.mjs'")
  })

  it('generates collection registry and query() factory', () => {
    const output = emitRuntimeModule([COLLECTION_MODEL], [
      { fileName: 'blog-post.en.mjs', content: '' },
    ])
    expect(output).toContain('_collectionRegistry')
    expect(output).toContain("'blog-post'")
    expect(output).toContain('export function query(model)')
    expect(output).toContain('new QueryBuilder(data)')
  })

  it('generates singleton registry and singleton() factory', () => {
    const output = emitRuntimeModule([SINGLETON_MODEL], [
      { fileName: 'hero.en.mjs', content: '' },
    ])
    expect(output).toContain('_singletonRegistry')
    expect(output).toContain('export function singleton(model)')
    expect(output).toContain('new SingletonAccessor(data)')
  })

  it('generates dictionary registry and dictionary() factory', () => {
    const output = emitRuntimeModule([DICTIONARY_MODEL], [
      { fileName: 'errors.en.mjs', content: '' },
    ])
    expect(output).toContain('_dictionaryRegistry')
    expect(output).toContain('export function dictionary(model)')
    expect(output).toContain('new DictionaryAccessor(data)')
  })

  it('generates document registry with aggregated arrays per locale', () => {
    const output = emitRuntimeModule([DOCUMENT_MODEL], [
      { fileName: 'blog-article--welcome.en.mjs', content: '' },
      { fileName: 'blog-article--about.en.mjs', content: '' },
      { fileName: 'blog-article--welcome.tr.mjs', content: '' },
    ])
    expect(output).toContain('export function document(model)')
    expect(output).toContain('new DocumentQuery(data)')
    // Both en slugs should be aggregated into same array
    expect(output).toContain("['en', [_blogArticleWelcomeEn, _blogArticleAboutEn]]")
    expect(output).toContain("['tr', [_blogArticleWelcomeTr]]")
  })

  it('generates all 4 kind registries when all kinds present', () => {
    const models = [COLLECTION_MODEL, SINGLETON_MODEL, DICTIONARY_MODEL, DOCUMENT_MODEL]
    const dataModules: DataModule[] = [
      { fileName: 'blog-post.en.mjs', content: '' },
      { fileName: 'hero.en.mjs', content: '' },
      { fileName: 'errors.en.mjs', content: '' },
      { fileName: 'blog-article--test.en.mjs', content: '' },
    ]
    const output = emitRuntimeModule(models, dataModules)
    expect(output).toContain('export function query(')
    expect(output).toContain('export function singleton(')
    expect(output).toContain('export function dictionary(')
    expect(output).toContain('export function document(')
  })

  it('skips registry for kinds with no models', () => {
    const output = emitRuntimeModule([COLLECTION_MODEL], [
      { fileName: 'blog-post.en.mjs', content: '' },
    ])
    expect(output).not.toContain('export function singleton(')
    expect(output).not.toContain('export function dictionary(')
    expect(output).not.toContain('export function document(')
  })

  it('inlines runtime class definitions', () => {
    const output = emitRuntimeModule([COLLECTION_MODEL], [
      { fileName: 'blog-post.en.mjs', content: '' },
    ])
    expect(output).toContain('class QueryBuilder')
    expect(output).toContain('class SingletonAccessor')
    expect(output).toContain('class DictionaryAccessor')
    expect(output).toContain('class DocumentQuery')
  })

  it('throws for unknown model in generated factory', () => {
    const output = emitRuntimeModule([COLLECTION_MODEL], [
      { fileName: 'blog-post.en.mjs', content: '' },
    ])
    expect(output).toContain('Unknown collection model')
  })
})

describe('emitRuntimeModule — relation metadata', () => {
  it('generates _relationMeta for models with relation fields', () => {
    const modelWithRels: ModelDefinition = {
      id: 'blog-post', name: 'Blog Post', kind: 'collection', domain: 'blog', i18n: true,
      fields: {
        title: { type: 'string', required: true },
        author: { type: 'relation', model: 'author', required: true },
        tags: { type: 'relations', model: 'tag' },
      },
    }
    const output = emitRuntimeModule([modelWithRels], [
      { fileName: 'blog-post.en.mjs', content: '' },
    ])
    expect(output).toContain('_relationMeta')
    expect(output).toContain("'blog-post'")
    expect(output).toContain("'author': { target: 'author', multi: false }")
    expect(output).toContain("'tags': { target: 'tag', multi: true }")
  })

  it('generates _resolveEntry function when relations exist', () => {
    const modelWithRels: ModelDefinition = {
      id: 'blog-post', name: 'Blog Post', kind: 'collection', domain: 'blog', i18n: true,
      fields: {
        author: { type: 'relation', model: 'author', required: true },
      },
    }
    const output = emitRuntimeModule([modelWithRels], [
      { fileName: 'blog-post.en.mjs', content: '' },
    ])
    expect(output).toContain('function _resolveEntry(model, id, locale)')
    expect(output).toContain('_collectionRegistry[model]')
  })

  it('passes relation meta and resolver to QueryBuilder constructor', () => {
    const modelWithRels: ModelDefinition = {
      id: 'blog-post', name: 'Blog Post', kind: 'collection', domain: 'blog', i18n: true,
      fields: {
        author: { type: 'relation', model: 'author', required: true },
      },
    }
    const output = emitRuntimeModule([modelWithRels], [
      { fileName: 'blog-post.en.mjs', content: '' },
    ])
    expect(output).toContain('new QueryBuilder(data, _relationMeta[model], _resolveEntry)')
  })

  it('does not generate relation meta declaration when no relations exist', () => {
    const output = emitRuntimeModule([COLLECTION_MODEL], [
      { fileName: 'blog-post.en.mjs', content: '' },
    ])
    expect(output).not.toContain('const _relationMeta')
    expect(output).not.toContain('function _resolveEntry')
    expect(output).toContain('new QueryBuilder(data)')
  })

  it('handles polymorphic relations (model: string[])', () => {
    const polyModel: ModelDefinition = {
      id: 'post', name: 'Post', kind: 'collection', domain: 'blog', i18n: false,
      fields: {
        ref: { type: 'relation', model: ['author', 'tag'] },
      },
    }
    const output = emitRuntimeModule([polyModel], [
      { fileName: 'post.en.mjs', content: '' },
    ])
    expect(output).toContain("'ref': { target: ['author', 'tag'], multi: false }")
  })

  it('inlined runtime includes include() and _resolveIncludes methods', () => {
    const output = emitRuntimeModule([COLLECTION_MODEL], [
      { fileName: 'blog-post.en.mjs', content: '' },
    ])
    expect(output).toContain('include(...fields)')
    expect(output).toContain('_resolveIncludes')
  })
})

describe('emitCjsWrapper', () => {
  it('generates CJS proxy with init() for collection models', () => {
    const output = emitCjsWrapper([COLLECTION_MODEL])
    expect(output).toContain("'use strict'")
    expect(output).toContain("import('./index.mjs')")
    expect(output).toContain('module.exports.query')
    expect(output).toContain('module.exports.init')
  })

  it('includes all present kinds in exports', () => {
    const output = emitCjsWrapper([COLLECTION_MODEL, SINGLETON_MODEL, DICTIONARY_MODEL, DOCUMENT_MODEL])
    expect(output).toContain('module.exports.query')
    expect(output).toContain('module.exports.singleton')
    expect(output).toContain('module.exports.dictionary')
    expect(output).toContain('module.exports.document')
  })

  it('omits missing kinds from exports', () => {
    const output = emitCjsWrapper([COLLECTION_MODEL])
    expect(output).not.toContain('module.exports.singleton')
    expect(output).not.toContain('module.exports.dictionary')
    expect(output).not.toContain('module.exports.document')
  })

  it('does not use top-level await (only uses .then())', () => {
    const output = emitCjsWrapper([COLLECTION_MODEL, SINGLETON_MODEL])
    // Code lines (not comments) should not contain await
    const codeLines = output.split('\n').filter(l => !l.trimStart().startsWith('//'))
    expect(codeLines.join('\n')).not.toContain('await ')
  })
})
