/* eslint-disable */
/* oxlint-disable */
// Auto-generated by @contentrain/query — do not edit manually
// Re-generate with: npx contentrain-query generate

export type ContentStatus = 'draft' | 'published' | 'in_review' | 'rejected' | 'archived'
export type WhereOp = 'eq' | 'ne' | 'gt' | 'gte' | 'lt' | 'lte' | 'in' | 'contains'

export interface DocsGuide {
  slug: string
  body: string
  category?: 'getting-started' | 'packages' | 'guides' | 'reference' | 'examples'
  description?: string
  order?: number
  title: string
}

export interface DocsGuides {
  slug: string
  body: string
  description?: string
  order?: number
  title: string
}

export interface DocsPackages {
  slug: string
  body: string
  description?: string
  order?: number
  title: string
}

export interface DocsReference {
  slug: string
  body: string
  description?: string
  order?: number
  title: string
}

export interface Faq {
  id: string
  answer: string
  category?: string
  order?: number
  question: string
}

export interface Hero {
  id: string
  cta_link: string
  cta_text: string
  image?: string
  subtitle?: string
  title: string
}

export interface Integrations {
  id: string
  category: 'framework' | 'platform' | 'tool' | 'cms'
  description: string
  difficulty?: number
  features?: { description?: string; icon?: string; title: string }[]
  is_official?: boolean
  logo?: string
  name: string
  order?: number
  slug: string
  supported_since?: string
  tags?: string[]
  website?: string
}

export interface Navigation {
  brand_name: string
  cta_link?: string
  cta_text?: string
}

export interface Pricing {
  id: string
  currency?: string
  features?: string[]
  highlighted?: boolean
  name: string
  period?: string
  price: number
}

export type ServeUiTexts = Record<string, string>

export interface Showcase {
  id: string
  attachment?: string
  author?: string | Hero
  body?: string
  brand_color?: string
  content?: string
  cover?: string
  demo_video?: string
  difficulty?: number
  discount?: number
  email?: string
  event_time?: string
  handle?: string
  html_body?: string
  is_active?: boolean
  logo_ref?: string
  phone?: string
  price?: number
  publish_date?: string
  related?: Array<string | Faq>
  snippet?: string
  status?: 'active' | 'inactive' | 'archived'
  stock?: number
  tags?: string[]
  title: string
  website?: string
}

export interface QueryBuilder<T> {
  locale(lang: string): QueryBuilder<T>
  where<K extends keyof T>(field: K, value: T[K]): QueryBuilder<T>
  where<K extends keyof T>(field: K, op: WhereOp, value: unknown): QueryBuilder<T>
  sort<K extends keyof T>(field: K, order?: 'asc' | 'desc'): QueryBuilder<T>
  limit(n: number): QueryBuilder<T>
  offset(n: number): QueryBuilder<T>
  include<K extends keyof T & string>(...fields: K[]): QueryBuilder<T>
  count(): number
  first(): T | undefined
  all(): T[]
}

export interface SingletonAccessor<T> {
  locale(lang: string): SingletonAccessor<T>
  include<K extends keyof T & string>(...fields: K[]): SingletonAccessor<T>
  get(): T
}

export interface DictionaryAccessor {
  locale(lang: string): DictionaryAccessor
  get(): Record<string, string>
  get(key: string): string | undefined
  get(key: string, params: Record<string, string | number>): string
}

export interface DocumentQuery<T> {
  locale(lang: string): DocumentQuery<T>
  where<K extends keyof T>(field: K, value: T[K]): DocumentQuery<T>
  where<K extends keyof T>(field: K, op: WhereOp, value: unknown): DocumentQuery<T>
  sort<K extends keyof T>(field: K, order?: 'asc' | 'desc'): DocumentQuery<T>
  include<K extends keyof T & string>(...fields: K[]): DocumentQuery<T>
  bySlug(slug: string): T | undefined
  count(): number
  first(): T | undefined
  all(): T[]
}

export declare function query(model: 'faq'): QueryBuilder<Faq>
export declare function query(model: 'hero'): QueryBuilder<Hero>
export declare function query(model: 'integrations'): QueryBuilder<Integrations>
export declare function query(model: 'pricing'): QueryBuilder<Pricing>
export declare function query(model: 'showcase'): QueryBuilder<Showcase>
export declare function query(model: string): QueryBuilder<Record<string, unknown>>

export declare function singleton(model: 'navigation'): SingletonAccessor<Navigation>
export declare function singleton(model: string): SingletonAccessor<Record<string, unknown>>

export declare function dictionary(model: 'serve-ui-texts'): DictionaryAccessor
export declare function dictionary(model: string): DictionaryAccessor

export declare function document(model: 'docs-guide'): DocumentQuery<DocsGuide>
export declare function document(model: 'docs-guides'): DocumentQuery<DocsGuides>
export declare function document(model: 'docs-packages'): DocumentQuery<DocsPackages>
export declare function document(model: 'docs-reference'): DocumentQuery<DocsReference>
export declare function document(model: string): DocumentQuery<Record<string, unknown>>

export interface ContentrainClient {
  query(model: 'faq'): QueryBuilder<Faq>
  query(model: 'hero'): QueryBuilder<Hero>
  query(model: 'integrations'): QueryBuilder<Integrations>
  query(model: 'pricing'): QueryBuilder<Pricing>
  query(model: 'showcase'): QueryBuilder<Showcase>
  query(model: string): QueryBuilder<Record<string, unknown>>
  singleton(model: 'navigation'): SingletonAccessor<Navigation>
  singleton(model: string): SingletonAccessor<Record<string, unknown>>
  dictionary(model: 'serve-ui-texts'): DictionaryAccessor
  dictionary(model: string): DictionaryAccessor
  document(model: 'docs-guide'): DocumentQuery<DocsGuide>
  document(model: 'docs-guides'): DocumentQuery<DocsGuides>
  document(model: 'docs-packages'): DocumentQuery<DocsPackages>
  document(model: 'docs-reference'): DocumentQuery<DocsReference>
  document(model: string): DocumentQuery<Record<string, unknown>>
}

export declare function createContentrainClient(): ContentrainClient

