/* eslint-disable */
/* oxlint-disable */
// Auto-generated by @contentrain/query — do not edit manually

const _defaultLocale = 'en'

import _docsGuideConcepts from './data/docs-guide--concepts.mjs'
import _docsGuideDemo from './data/docs-guide--demo.mjs'
import _docsGuideEcosystem from './data/docs-guide--ecosystem.mjs'
import _docsGuideGettingStarted from './data/docs-guide--getting-started.mjs'
import _docsGuideIndex from './data/docs-guide--index.mjs'
import _docsGuideStudio from './data/docs-guide--studio.mjs'
import _docsGuidesEmbeddingMcp from './data/docs-guides--embedding-mcp.mjs'
import _docsGuidesFrameworks from './data/docs-guides--frameworks.mjs'
import _docsGuidesHttpTransport from './data/docs-guides--http-transport.mjs'
import _docsGuidesI18n from './data/docs-guides--i18n.mjs'
import _docsGuidesNormalize from './data/docs-guides--normalize.mjs'
import _docsGuidesProviders from './data/docs-guides--providers.mjs'
import _docsGuidesServeUi from './data/docs-guides--serve-ui.mjs'
import _docsPackagesCli from './data/docs-packages--cli.mjs'
import _docsPackagesMcp from './data/docs-packages--mcp.mjs'
import _docsPackagesRules from './data/docs-packages--rules.mjs'
import _docsPackagesSdk from './data/docs-packages--sdk.mjs'
import _docsPackagesTypes from './data/docs-packages--types.mjs'
import _docsReferenceConfig from './data/docs-reference--config.mjs'
import _docsReferenceFieldTypes from './data/docs-reference--field-types.mjs'
import _docsReferenceModelKinds from './data/docs-reference--model-kinds.mjs'
import _docsReferenceProviders from './data/docs-reference--providers.mjs'
import _faqEn from './data/faq.en.mjs'
import _heroEn from './data/hero.en.mjs'
import _heroTr from './data/hero.tr.mjs'
import _integrationsEn from './data/integrations.en.mjs'
import _integrationsTr from './data/integrations.tr.mjs'
import _navigationEn from './data/navigation.en.mjs'
import _navigationTr from './data/navigation.tr.mjs'
import _pricingEn from './data/pricing.en.mjs'
import _serveUiTextsEn from './data/serve-ui-texts.en.mjs'
import _showcaseEn from './data/showcase.en.mjs'

// ─── Runtime Helpers ───

function _applyWhere(item, clause) {
  const val = item[clause.field];
  switch (clause.op) {
    case 'eq': return Array.isArray(val) ? val.includes(clause.value) : val === clause.value;
    case 'ne': return Array.isArray(val) ? !val.includes(clause.value) : val !== clause.value;
    case 'gt': return val > clause.value;
    case 'gte': return val >= clause.value;
    case 'lt': return val < clause.value;
    case 'lte': return val <= clause.value;
    case 'in': return Array.isArray(clause.value) && clause.value.includes(val);
    case 'contains': {
      if (typeof val === 'string') return val.includes(clause.value);
      if (Array.isArray(val)) return val.includes(clause.value);
      return false;
    }
    default: return true;
  }
}

// ─── Runtime Classes ───

class QueryBuilder {
  constructor(data, relationMeta, resolver, defaultLocale) { this._data = data; this._filters = []; this._sortField = null; this._sortOrder = 'asc'; this._limit = null; this._offset = 0; this._locale = null; this._includes = []; this._relationMeta = relationMeta || {}; this._resolver = resolver || null; this._defaultLocale = defaultLocale || null; }
  locale(lang) { this._locale = lang; return this; }
  where(field, opOrValue, value) { if (value !== undefined) { this._filters.push({ field, op: opOrValue, value }); } else { this._filters.push({ field, op: 'eq', value: opOrValue }); } return this; }
  sort(field, order = 'asc') { this._sortField = field; this._sortOrder = order; return this; }
  limit(n) { this._limit = n; return this; }
  offset(n) { this._offset = n; return this; }
  include(...fields) { this._includes.push(...fields); return this; }
  count() { return this.all().length; }
  all() {
    let items; if (this._locale) { items = [...(this._data.get(this._locale) ?? [])]; } else if (this._defaultLocale && this._data.has(this._defaultLocale)) { items = [...this._data.get(this._defaultLocale)]; } else { items = [...(this._data.get(this._data.keys().next().value) ?? [])]; }
    for (const clause of this._filters) items = items.filter(item => _applyWhere(item, clause));
    if (this._sortField) { const sf = this._sortField; const d = this._sortOrder === 'asc' ? 1 : -1; items.sort((a, b) => { const va = a[sf], vb = b[sf]; if (va == null && vb == null) return 0; if (va == null) return d; if (vb == null) return -d; return va < vb ? -d : va > vb ? d : 0; }); }
    if (this._offset > 0 || this._limit !== null) { const end = this._limit !== null ? this._offset + this._limit : undefined; items = items.slice(this._offset, end); }
    if (this._includes.length > 0 && this._resolver) { items = items.map(item => this._resolveIncludes(item)); }
    return items;
  }
  first() { return this.all()[0]; }
  _resolveIncludes(item) {
    const resolved = { ...item };
    const _loc = this._locale ?? this._defaultLocale;
    for (const field of this._includes) {
      const meta = this._relationMeta[field]; if (!meta) continue;
      const targets = Array.isArray(meta.target) ? meta.target : [meta.target];
      if (meta.multi) { const ids = item[field]; if (Array.isArray(ids)) { resolved[field] = ids.map(id => { if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, _loc); if (r) return r; } return id; } if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, _loc); if (r) return r; } return id; }); } }
      else { const id = item[field]; if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, _loc); if (r) { resolved[field] = r; break; } } } else if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, _loc); if (r) resolved[field] = r; } }
    }
    return resolved;
  }
}

class SingletonAccessor {
  constructor(data, defaultLocale, relationMeta, resolveEntry) { this._data = data; this._locale = null; this._defaultLocale = defaultLocale || null; this._includes = []; this._relationMeta = relationMeta || {}; this._resolver = resolveEntry; }
  locale(lang) { this._locale = lang; return this; }
  include(...fields) { this._includes.push(...fields); return this; }
  get() {
    const locale = this._locale || this._defaultLocale;
    let d = locale ? this._data.get(locale) : undefined;
    if (!d) { const key = this._data.keys().next().value; d = key !== undefined ? this._data.get(key) : undefined; }
    if (!d) throw new Error('No data available');
    if (this._includes.length > 0 && this._resolver) return this._resolveIncludes(d, locale || 'en');
    return d;
  }
  _resolveIncludes(item, locale) {
    const resolved = { ...item };
    for (const field of this._includes) {
      const meta = this._relationMeta[field]; if (!meta) continue;
      const targets = Array.isArray(meta.target) ? meta.target : [meta.target];
      if (meta.multi) { const ids = item[field]; if (Array.isArray(ids)) { resolved[field] = ids.map(id => { if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, locale); if (r) return r; } return id; } if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, locale); if (r) return r; } return id; }); } }
      else { const id = item[field]; if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, locale); if (r) { resolved[field] = r; break; } } } else if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, locale); if (r) resolved[field] = r; } }
    }
    return resolved;
  }
}

class DictionaryAccessor {
  constructor(data, defaultLocale) { this._data = data; this._locale = null; this._defaultLocale = defaultLocale || null; }
  locale(lang) { this._locale = lang; return this; }
  get(key, params) {
    let dict; if (this._locale) { dict = this._data.get(this._locale) ?? {}; } else if (this._defaultLocale && this._data.has(this._defaultLocale)) { dict = this._data.get(this._defaultLocale); } else { const loc = this._data.keys().next().value; dict = this._data.get(loc) ?? {}; }
    if (key === undefined) return dict;
    const val = dict[key];
    if (val === undefined) return undefined;
    if (params) return val.replace(/\{(\w+)\}/g, (m, k) => { const v = params[k]; return v !== undefined ? String(v) : m; });
    return val;
  }
}

class DocumentQuery {
  constructor(data, relationMeta, resolver, defaultLocale) { this._data = data; this._filters = []; this._sortField = null; this._sortOrder = 'asc'; this._locale = null; this._includes = []; this._relationMeta = relationMeta || {}; this._resolver = resolver || null; this._defaultLocale = defaultLocale || null; }
  locale(lang) { this._locale = lang; return this; }
  where(field, opOrValue, value) { if (value !== undefined) { this._filters.push({ field, op: opOrValue, value }); } else { this._filters.push({ field, op: 'eq', value: opOrValue }); } return this; }
  sort(field, order = 'asc') { this._sortField = field; this._sortOrder = order; return this; }
  include(...fields) { this._includes.push(...fields); return this; }
  bySlug(slug) {
    const items = this._resolveData(); const item = items.find(x => x.slug === slug);
    if (item && this._includes.length > 0 && this._resolver) return this._resolveIncludes(item);
    return item;
  }
  count() { return this.all().length; }
  first() { return this.all()[0]; }
  all() { let items = this._resolveData(); for (const clause of this._filters) items = items.filter(item => _applyWhere(item, clause)); if (this._sortField) { const sf = this._sortField; const d = this._sortOrder === 'asc' ? 1 : -1; items.sort((a, b) => { const va = a[sf], vb = b[sf]; if (va == null && vb == null) return 0; if (va == null) return d; if (vb == null) return -d; return va < vb ? -d : va > vb ? d : 0; }); } if (this._includes.length > 0 && this._resolver) { items = items.map(item => this._resolveIncludes(item)); } return items; }
  _resolveData() { let key; if (this._locale) { key = this._locale; } else if (this._defaultLocale && this._data.has(this._defaultLocale)) { key = this._defaultLocale; } else { key = this._data.keys().next().value; } return [...(this._data.get(key) ?? [])]; }
  _resolveIncludes(item) {
    const resolved = { ...item };
    const _loc = this._locale ?? this._defaultLocale;
    for (const field of this._includes) {
      const meta = this._relationMeta[field]; if (!meta) continue;
      const targets = Array.isArray(meta.target) ? meta.target : [meta.target];
      if (meta.multi) { const ids = item[field]; if (Array.isArray(ids)) { resolved[field] = ids.map(id => { if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, _loc); if (r) return r; } return id; } if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, _loc); if (r) return r; } return id; }); } }
      else { const id = item[field]; if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, _loc); if (r) { resolved[field] = r; break; } } } else if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, _loc); if (r) resolved[field] = r; } }
    }
    return resolved;
  }
}

// ─── Data Registry ───

// ─── Relation Resolver ───

function _resolveEntry(model, id, locale) {
  const localeKeys = locale ? [locale, '_default'] : ['_default']
  for (const localeKey of localeKeys) {
    const colData = _collectionRegistry[model]?.get(localeKey)
    if (colData) { const e = colData.find(x => x.id === id); if (e) return e; }
    const docData = _documentRegistry[model]?.get(localeKey)
    if (docData) { const e = docData.find(x => x.slug === id); if (e) return e; }
  }
  return undefined
}

const _relationMeta = {
  'showcase': {
    'author': { target: 'hero', multi: false },
    'related': { target: 'faq', multi: true },
  },
}

const _collectionRegistry = {
  'faq': new Map([
    ['en', _faqEn],
  ]),
  'hero': new Map([
    ['en', _heroEn],
    ['tr', _heroTr],
  ]),
  'integrations': new Map([
    ['en', _integrationsEn],
    ['tr', _integrationsTr],
  ]),
  'pricing': new Map([
    ['en', _pricingEn],
  ]),
  'showcase': new Map([
    ['en', _showcaseEn],
  ]),
}

export function query(model) {
  const data = _collectionRegistry[model]
  if (!data) throw new Error(`Unknown collection model: "${model}"`)
  return new QueryBuilder(data, _relationMeta[model], _resolveEntry, _defaultLocale)
}

const _singletonRegistry = {
  'navigation': new Map([
    ['en', _navigationEn],
    ['tr', _navigationTr],
  ]),
}

export function singleton(model) {
  const data = _singletonRegistry[model]
  if (!data) throw new Error(`Unknown singleton model: "${model}"`)
  return new SingletonAccessor(data, _defaultLocale, _relationMeta[model], _resolveEntry)
}

const _dictionaryRegistry = {
  'serve-ui-texts': new Map([
    ['en', _serveUiTextsEn],
  ]),
}

export function dictionary(model) {
  const data = _dictionaryRegistry[model]
  if (!data) throw new Error(`Unknown dictionary model: "${model}"`)
  return new DictionaryAccessor(data, _defaultLocale)
}

const _doc_docs_guide = new Map([
  ['_default', [_docsGuideConcepts, _docsGuideDemo, _docsGuideEcosystem, _docsGuideGettingStarted, _docsGuideIndex, _docsGuideStudio]],
])
const _doc_docs_guides = new Map([
  ['_default', [_docsGuidesEmbeddingMcp, _docsGuidesFrameworks, _docsGuidesHttpTransport, _docsGuidesI18n, _docsGuidesNormalize, _docsGuidesProviders, _docsGuidesServeUi]],
])
const _doc_docs_packages = new Map([
  ['_default', [_docsPackagesCli, _docsPackagesMcp, _docsPackagesRules, _docsPackagesSdk, _docsPackagesTypes]],
])
const _doc_docs_reference = new Map([
  ['_default', [_docsReferenceConfig, _docsReferenceFieldTypes, _docsReferenceModelKinds, _docsReferenceProviders]],
])

const _documentRegistry = {
  'docs-guide': _doc_docs_guide,
  'docs-guides': _doc_docs_guides,
  'docs-packages': _doc_docs_packages,
  'docs-reference': _doc_docs_reference,
}

export function document(model) {
  const data = _documentRegistry[model]
  if (!data) throw new Error(`Unknown document model: "${model}"`)
  return new DocumentQuery(data, _relationMeta[model], _resolveEntry, _defaultLocale)
}

