// Auto-generated by @contentrain/query — do not edit manually
// Re-generate with: npx contentrain-query generate

export type ContentStatus = 'draft' | 'published' | 'in_review' | 'rejected' | 'archived'

export interface Faq {
  id: string
  answer: string
  category?: string
  order?: number
  question: string
}

export interface Hero {
  id: string
  cta_link: string
  cta_text: string
  image?: string
  subtitle?: string
  title: string
}

export interface Navigation {
  brand_name: string
  cta_link?: string
  cta_text?: string
}

export interface Pricing {
  id: string
  currency?: string
  features?: string[]
  highlighted?: boolean
  name: string
  period?: string
  price: number
}

export type ServeUiTexts = Record<string, string>

export interface Showcase {
  id: string
  attachment?: string
  author?: string
  body?: string
  brand_color?: string
  content?: string
  cover?: string
  demo_video?: string
  difficulty?: number
  discount?: number
  email?: string
  event_time?: string
  handle?: string
  html_body?: string
  is_active?: boolean
  logo_ref?: string
  phone?: string
  price?: number
  publish_date?: string
  related?: string[]
  snippet?: string
  status?: 'active' | 'inactive' | 'archived'
  stock?: number
  tags?: string[]
  title: string
  website?: string
}

export interface QueryBuilder<T> {
  locale(lang: string): QueryBuilder<T>
  where<K extends keyof T>(field: K, value: T[K]): QueryBuilder<T>
  sort<K extends keyof T>(field: K, order?: 'asc' | 'desc'): QueryBuilder<T>
  limit(n: number): QueryBuilder<T>
  offset(n: number): QueryBuilder<T>
  include(...fields: string[]): QueryBuilder<T>
  first(): T | undefined
  all(): T[]
}

export interface SingletonAccessor<T> {
  locale(lang: string): SingletonAccessor<T>
  include(...fields: string[]): SingletonAccessor<T>
  get(): T
}

export interface DictionaryAccessor {
  locale(lang: string): DictionaryAccessor
  get(): Record<string, string>
  get(key: string): string | undefined
}

export interface DocumentQuery<T> {
  locale(lang: string): DocumentQuery<T>
  where<K extends keyof T>(field: K, value: T[K]): DocumentQuery<T>
  include(...fields: string[]): DocumentQuery<T>
  bySlug(slug: string): T | undefined
  first(): T | undefined
  all(): T[]
}

export declare function query(model: 'faq'): QueryBuilder<Faq>
export declare function query(model: 'hero'): QueryBuilder<Hero>
export declare function query(model: 'pricing'): QueryBuilder<Pricing>
export declare function query(model: 'showcase'): QueryBuilder<Showcase>
export declare function query(model: string): QueryBuilder<Record<string, unknown>>

export declare function singleton(model: 'navigation'): SingletonAccessor<Navigation>
export declare function singleton(model: string): SingletonAccessor<Record<string, unknown>>

export declare function dictionary(model: 'serve-ui-texts'): DictionaryAccessor
export declare function dictionary(model: string): DictionaryAccessor

export declare function document(model: string): DocumentQuery<Record<string, unknown>>

export interface ContentrainClient {
  query(model: 'faq'): QueryBuilder<Faq>
  query(model: 'hero'): QueryBuilder<Hero>
  query(model: 'pricing'): QueryBuilder<Pricing>
  query(model: 'showcase'): QueryBuilder<Showcase>
  query(model: string): QueryBuilder<Record<string, unknown>>
  singleton(model: 'navigation'): SingletonAccessor<Navigation>
  singleton(model: string): SingletonAccessor<Record<string, unknown>>
  dictionary(model: 'serve-ui-texts'): DictionaryAccessor
  dictionary(model: string): DictionaryAccessor
  document(model: string): DocumentQuery<Record<string, unknown>>
}

export declare function createContentrainClient(): ContentrainClient

